### ISSUE TITLE
AppleKeyStore: Operation Failed

### ISSUE THREAD

**Issue by s-cd** [HBlanqueto/T480-hackintosh#11]
I have been trying with multiple efis, including making my own and all of them seem to fail at that part, seem to try everything but I got nothing

**Comment by HBlanqueto** [comment]
I don't know what the cause of your problem could be or what it refers to, I don't think I'll risk moving any of my EFI to solve it. I don't know what has been presented to me in my case.

Check if your BIOS or some other component external to your ThinkPad may be causing it.
