### ISSUE TITLE
Have you used Thunderbolt?

### ISSUE THREAD

**Issue by HBlanqueto** [HBlanqueto/T480-hackintosh#3]
Hi! The main point of this Issue is to share any experience using the Thunderbolt entry using a Dock Station or directly with a monitor or whatever you use It. I invite you to share your opinion using this feature.

So, **have you tried Thunderbolt with Hackintosh? did you used a Dock Station?** 

I investigated a few references people using Thunderbolt and it seems to be stable.
- [Dell Latitude 7490 - Mac OS Big Sur - thunderbolt dock working](https://www.reddit.com/r/hackintosh/comments/xb0kgd/dell_latitude_7490_mac_os_big_sur_thunderbolt/)
- [add thunderbolt port dell g7 hackintosh dual display dock with thunderbolt uad-English](https://www.youtube.com/watch?v=kksyGVgLYJ0)

**EDIT 10/10th/2023**
 ✅ All is working (at least for me)

**Comment by bweh** [comment]
For some reason, my thunderbolt does not work even though my NVM version is 23.0. I had it working briefly a couple hours ago (and my eGPU was recognized and working) but after several restarts, I constantly see "Thunderbolt/USB4: No drivers are loaded." in System Report. And JHL6240 doesn't show up in Hackintool either.

I found someone with the [same issue](https://github.com/pierpaolodimarzo/ThinkPad-T480/issues/21) in pierpaolodimarzo's repo.

Is this an issue with hackintosh? I don't have windows dual booted but my TB3 was working well a few days ago when I tried it on windows.

**Comment by HBlanqueto** [comment]
> Is this an issue with hackintosh? I don't have windows dual booted but my TB3 was working well a few days ago when I tried it on windows.

I want to think hackintosh itself doesn't work perfectly and this could be something that cannot be solved in a long time. I founded this other [repo](https://github.com/hexart/T480-OpenCore-Hackintosh) older than pierpaolodimarzo's repo and mine.

I checked hexart's EFI and he got TB working, on the other hand same issue with [sleeping](https://github.com/hexart/T480-OpenCore-Hackintosh/issues/13) is present here.

**What's your Bios version?**

**Comment by bweh** [comment]
Ah darn that’s unfortunate because everything else works really well.

My bios version is N24ET73W (1.48), date is 2023-06-13. I’ve made by bios settings identical to the ones in all 3 readmes.

**Comment by bweh** [comment]
Hey, It actually shows up and works when I set `Support in Pre Boot Environment > Thunderbolt(TM) device` to disabled. Not sure if that's supposed to happen...

**Comment by HBlanqueto** [comment]
> My bios version is N24ET73W (1.48), date is 2023-06-13. I’ve made by bios settings identical to the ones in all 3 readmes.

Mine is N24ET74P (1.49), I recently updated from Lenovo Vantage.


> Hey, It actually shows up and works when I set `Support in Pre Boot Environment > Thunderbolt(TM) device` to disabled. Not sure if that's supposed to happen.
> 
> I re-tried with it set to enabled, and it does not show up. Interesting.

That's... unexpected, I always had it `enabled` as pierpaolodimarzo's README and sometimes TB didn't show up in System Report but in some minutes got enabled again. Let me know if you see more differences with Support in Pre Boot Environment disabled. 

Did TB work after sleeping the Thinkpad?

**Comment by bweh** [comment]
Really odd, I enabled it again and thunderbolt shows up and is working. I guess it's random. and yes, it worked after sleep.

**Comment by michal161** [comment]
Hmmm i just installed macos on T480s and somehow also have issues with thunderbolt not showing in system information.

**Comment by HBlanqueto** [comment]
## Testing Thunderbolt

After many time I got able to buy a [dock](https://articulo.mercadolibre.com.mx/MLM-1972430400-hub-usb-c-13-en-1-wavlink-30-docking-station-4k-hdmi-dp-pd-_JM?quantity=1) for my ThinkPad, all seems working with no issue. What do I refer with "no issue"?

<img src="https://raw.githubusercontent.com/HBlanqueto/T480-hackintosh/main/.github/assets/Thunderbolt1.jpg" alt="img">

Sometimes in the System Report app Thunderbolt is not showing for some reason, however is still working and do not present any issue here, the video is working in the second screen, ethernet and other stuff I connected. I teste with "sleep" mode and "clam shell" mode and the HDMI, Ethernet, Mouse and Keyboard are recognized inmediatly after wake up.

<img src="https://raw.githubusercontent.com/HBlanqueto/T480-hackintosh/main/.github/assets/SysReportThunderbolt.jpg" alt="img">

I want to think that is "normal" that does not show properly in the macOS system due to this is a hackintosh and no properly Apple's hardware. At least in the T480 all is working in this case.

<img src="https://raw.githubusercontent.com/HBlanqueto/T480-hackintosh/main/.github/assets/Thunderbolt2.jpg" alt="img">
