### ISSUE TITLE
Sidecar showing black screen on ipad

### ISSUE THREAD

**Issue by Princeaddo1199** [HBlanqueto/T480-hackintosh#5]
Sidecar connects alright but the ipad screen remains black 
![16941949036352586000806856289654](https://github.com/HBlanqueto/T480-hackintosh/assets/117764655/013c0fd6-8fed-4959-96cb-77efe3ce0cfe)

**Comment by HBlanqueto** [comment]
Hello! Thanks for opening this issue, I need more information about this. Are you using the SideCar wirelsss or connected by usb?

**Comment by Princeaddo1199** [comment]
It's connected via usb

**Comment by HBlanqueto** [comment]
Looking some information about this, It is supposed that all usb mapping are correct. I noticed pierpaolodimarzo's repo uses `MacBookPro14,1` for serial, generate a new SMBios with that value.

Just make sure it has Apple coverage.

If this work I will change the `MacBookPro15,2` in the documentation for the new one.

**Comment by Princeaddo1199** [comment]
Still didn't work
