### ISSUE TITLE
Freezes and shuts down when connected to WiFi

### ISSUE THREAD

**Issue by bweh** [HBlanqueto/T480-hackintosh#6]
Whenever I input the password for WiFi, it freezes and shuts down. I tried replacing with a different version of AirportItlwm but haven’t gotten it to work.

I was on macOS Monterey 12.6.8
i5-8350U, same wifi card as the one listed in the readme

any ideas?

**Comment by HBlanqueto** [comment]
Hi! Thanks for telling me the issue, I'll install Monterey to check what's going on here. I have some questions for you.

-  This happens after installing the system.
-  Did you have any problems with the installation process?

As I read, you changed the kext to the Monterey version. This will sound weird, but could you try using the one that is defaulted in my EFI folder? I know it's for Ventura; however, I have a memory of using it and It just worked.

Try it and tell me if something weird happens again. 🤔

**Comment by bweh** [comment]
Thanks for the reply. Yes it happens after installation. Interestingly, I didn’t have any issues with the installation process. I will try yours and will report back 👍🏻

**Comment by bweh** [comment]
I tried the latest EFI release, but I have the same issue. Here is a video of it (sorry about the quality)

https://dropover.cloud/68749f

**Comment by HBlanqueto** [comment]
Hi! There is a new EFI in release [MontereyFixup.zip](https://github.com/HBlanqueto/T480-hackintosh/releases/tag/0.9.5)

Report back if you get successful or has others issue, I've installed the system and got same issue during boot (I couldn't start the system).

**What happened here?**
Some weeks ago Ventura got an update that disabled bluetooth and wifi on Intel Cards, I've been using two custom kext (AirportItlwm and IntelBluetoothFirmware) which has some patches and I haven't changed them in a while.

I'm going to update default EFI in some days to see if using original kext I don't encounter another problem.

**Comment by bweh** [comment]
Thank you for the update. Wifi is working and has been stable for about 20 minutes now.

**Comment by HBlanqueto** [comment]
Excelent, I'll close the issue. Enjoy the system and any other problem tell me. 😊
