### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by doniprdna** [HBlanqueto/T480-hackintosh#7]
Thanks for sharing this EFI.
I'm using this efi on t480 i5 8250 (dualboot windows), with bcm94360ng wifi card installed. Since it should work native, I delete the wifi and bluetooth kext, but I have problem with wifi. I only get 1 Mbps download and upload. When i use windows i get 45 Mbps download and 20 Mbps upload.
And i cant join to wifi that have web login portal.
Is there any solution to this? Thanks

**Comment by HBlanqueto** [comment]
I'm going to be honest, I don't have idea what's going on there. I don't support broadcom cards so I don't have a way to test and fix it in a while.

Try using the old valonix's EFI folder with the broadcom support or check next post to try something, however try using broadcom kext to see any changes in wifi performance.

- https://www.reddit.com/r/hackintosh/comments/ll5j7n/slow_wifi_broadcom_bcm43xx/?rdt=39747
- https://www.reddit.com/r/hackintosh/comments/h7nlq5/hackintosh_slow_wifi_speeds_catalina/
- https://www.reddit.com/r/hackintosh/comments/3f5vcz/windows_10_drivers_for_bcm94360cd_wifibt_card/
