### ISSUE TITLE
Freezes and shuts down when connected to WiFi

### ISSUE THREAD

**Issue by lriverawong** [HBlanqueto/T480-hackintosh#8]
Hello
I had a problem where I had the machine freeze then reboot on `macOS Monterrey` when I tried to connect to wifi. I saw the other [issue](https://github.com/HBlanqueto/T480-hackintosh/issues/6) and saw that the latest [release - SourceCode.zip](https://github.com/HBlanqueto/T480-hackintosh/releases/tag/0.9.5) was mentioned but it didn't fix my issue.

The way I got it to work was downloading the latest [Airportitwlm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0) from the source. I kept all the other kexts except that one and it then worked.

I don't have a way to compare the `kexts` but it may be possible that the one in the latest release is still broken.

For reference I am using an `Intel AC 8265` card.

Thanks

**Comment by HBlanqueto** [comment]
My EFI has by default Ventura or Sonoma Airportitwlm versions, It's indeed to replace to the correct one version you used, in order avoid problems. I mention that in the in the release's README.


But, did you have any other problem? Which EFI did you download, the stable or testing?
