### ISSUE TITLE
ThinkPad X280 Ventura

### ISSUE THREAD

**Issue by loll70** [HBlanqueto/T480-hackintosh#9]
I successfully installed but thunderbolt is not working. 
Checking my device path in IOreg, i see I am on PCI0.RP01. Changing this in the thunderbolt SSDT didn't solve the issue.

**Comment by HBlanqueto** [comment]
Check this [EFI](https://github.com/waldir-xam/x280-Hackintosh) I found, I wish this could help you with the thunderbolt issue.

Let me know if you have an improvement.
